language: go

sudo: true
dist: xenial
addons:
  hosts:
    - example.letsencrypt.org
    - elpmaxe.letsencrypt.org

go:
  - "1.11.x"

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  # TODO(#204): Change back to cloning master once Certbot omits keyAuthorization.
  - git clone --depth=1 -b no-keyauthorization https://github.com/certbot/certbot
  - cd certbot
  - ./certbot-auto --os-packages-only -n
  - ./tools/venv.py
  - . venv/bin/activate
  - cd -

# Override the base install phase so that the project can be installed using
# `-mod=vendor` to use the vendored dependencies
install:
  - go install -v -mod=vendor ./...

before_script:
  - pebble &

script:
  - go vet -mod=vendor ./...
  - REQUESTS_CA_BUNDLE=./test/certs/pebble.minica.pem python ./test/chisel2.py example.letsencrypt.org elpmaxe.letsencrypt.org

deploy:
  - provider: script
    script: bash .ci/publish_linux.sh
    skip_cleanup: true
    on:
      repo: letsencrypt/pebble
      tags: true
