image: Visual Studio 2017

hosts:
  example.letsencrypt.org: 127.0.0.1
  elpmaxe.letsencrypt.org: 127.0.0.1

environment:
  GO111MODULE: on
  GOPATH: C:\gopath
  PATH: C:\Python37;C:\msys64\mingw64\bin\;%PATH%

install:
  # TODO(#204): Change back to cloning master once Certbot omits keyAuthorization.
  - git clone --depth=1 -b no-keyauthorization-windows https://github.com/certbot/certbot
  - cd certbot
  - python tools\venv3.py
  - venv3\Scripts\activate.bat
  - cd ..

build_script:
  - go install -v -mod=vendor ./...

after_build:
  - ps: $PebbleProcess = Start-Process C:\gopath\bin\pebble.exe -PassThru

test_script:
  - go mod download
  - go test -mod=vendor -v -race ./...
  - cmd /c "set REQUESTS_CA_BUNDLE=./test/certs/pebble.minica.pem && python .\test\chisel2.py example.letsencrypt.org elpmaxe.letsencrypt.org"

deploy_script:
  - ps: .ci\publish_windows.ps1

on_finish:
  - ps: Stop-Process -Id $PebbleProcess.Id
