image: Visual Studio 2017

branches:
  only:
    - windows

hosts:
  example.letsencrypt.org: 127.0.0.1
  elpmaxe.letsencrypt.org: 127.0.0.1

environment:
  DOCKER_USER:
    secure: f+rx7+08JPIM/MAFC5YLew==
  DOCKER_PASS:
    secure: 2WgIPEABjxf1fjwGLEd7Lg==
  GO111MODULE: on
  GOPATH: C:\gopath
  REQUESTS_CA_BUNDLE: test\certs\pebble.minica.pem

install:
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  - git clone https://github.com/adferrand/certbot --branch fix-pipstrap-on-windows
  - cd certbot
  - python tools\venv3.py
  - venv3\Scripts\activate.bat
  - cd ..

build_script:
  - go install -v -mod=vendor ./...
  - ps: $PebbleProcess = Start-Process pebble -PassThru

test_script:
  - go vet ./...
  - python .\test\chisel2.py example.letsencrypt.org elpmaxe.letsencrypt.org

deploy_script:
  - call .ci\publish_windows.bat

on_finish:
  - ps: Stop-Process -Id $PebbleProcess.Id
