image: Visual Studio 2017

hosts:
  example.letsencrypt.org: 127.0.0.1
  elpmaxe.letsencrypt.org: 127.0.0.1

environment:
  GO111MODULE: on
  GOPATH: C:\gopath

install:
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  # TODO(#204): Change back to cloning master once Certbot omits keyAuthorization.
  - git clone --depth=1 -b no-keyauthorization https://github.com/certbot/certbot
  - cd certbot
  - python tools\venv3.py
  - venv3\Scripts\activate.bat
  - cd ..

build_script:
  - bash: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
  - set GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - set GO111MODULE=off go get github.com/mattn/goveralls
  - go install -v -mod=vendor ./...

after_build:
  - ps: $PebbleProcess = Start-Process C:\gopath\bin\pebble.exe -PassThru

test_script:
  - go mod download
  - golangci-lint run
  - go test -mod=vendor -v -race -covermode=atomic -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service=appveyor
  - set REQUESTS_CA_BUNDLE=test\certs\pebble.minica.pem
  - python .\test\chisel2.py example.letsencrypt.org elpmaxe.letsencrypt.org

deploy_script:
  - ps: .ci\publish_windows.ps1

on_finish:
  - ps: Stop-Process -Id $PebbleProcess.Id
