image: Visual Studio 2017

hosts:
  example.letsencrypt.org: 127.0.0.1
  elpmaxe.letsencrypt.org: 127.0.0.1

environment:
  GO111MODULE: on
  GOPATH: C:\gopath
  PATH: C:\Python37;C:\msys64\mingw64\bin\;%PATH%

install:
  # TODO(#204): Change back to cloning master once Certbot omits keyAuthorization.
  - git clone --depth=1 -b no-keyauthorization-windows https://github.com/certbot/certbot
  - cd certbot
  - python tools\venv3.py
  - venv3\Scripts\activate.bat
  - cd ..

build_script:
  # Install `cover` and `goveralls` without `GO111MODULE` enabled so that we
  # don't download ct-woodpecker dependencies and just put the tools in our
  # gobin.
  - set GO111MODULE=off && go get golang.org/x/tools/cmd/cover && set GO111MODULE=on
  - set GO111MODULE=off && go get github.com/mattn/goveralls && set GO111MODULE=on
  - go install -v -mod=vendor ./...

after_build:
  - ps: $PebbleProcess = Start-Process C:\gopath\bin\pebble.exe -PassThru

test_script:
  - go mod download
  # Run project unit tests (with the race detector enabled and atomic
  # coverage profile collection)
  - go test -mod=vendor -v -race -covermode=atomic -coverprofile=coverage.out ./...
  # Upload collected coverage profile to goveralls
  - goveralls -coverprofile=coverage.out -service=appveyor
  # Perform a test issuance with chisel2.py
  - cmd /c "set REQUESTS_CA_BUNDLE=./test/certs/pebble.minica.pem && python .\test\chisel2.py example.letsencrypt.org elpmaxe.letsencrypt.org"

deploy_script:
  - ps: .ci\publish_windows.ps1

on_finish:
  - ps: Stop-Process -Id $PebbleProcess.Id
